### ISSUE TITLE
ImportError: cannot import name 'IEPlugin'

### ISSUE THREAD

**Issue by Kelly-ZH** [nullbyte91/Computer-Pointer-Controller#1]
- python3.6.5
- window10
-pycharm
 I run the code in windows environment, but there is  an error like this
>   File "C:\Users\Administrator.DESKTOP-TI37VJ6\Desktop\Computer-Pointer-Controller-master\utils\ie_module.py", line 4, in <module>
    from openvino.inference_engine import IEPlugin
ImportError: cannot import name 'IEPlugin'
Could you help me to find out the mistakes? Thank you very much.

**Comment by nullbyte91** [comment]
@Kelly-ZH You have to install OpenVino tool kit https://github.com/nullbyte91/Computer-Pointer-Controller#prerequisites

**Comment by Kelly-ZH** [comment]
> @Kelly-ZH You have to install OpenVino tool kit https://github.com/nullbyte91/Computer-Pointer-Controller#prerequisites

Thank you for your reply, I run the code in windows environment,  and it is the tutorial step of the Linux.
